import { GraphQLClient } from 'graphql-request';
import * as Dom from 'graphql-request/dist/types.dom';
import gql from 'graphql-tag';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /**
   * Define a Relay Cursor type:
   * https://relay.dev/graphql/connections.htm#sec-Cursor
   */
  Cursor: any;
};

export type Card = Node & {
  __typename?: 'Card';
  ancestors?: Maybe<Array<Card>>;
  cardSpecialColor?: Maybe<CardSpecialColor>;
  cardSpecialColorID?: Maybe<Scalars['ID']>;
  cardType: CardType;
  cardTypeID: Scalars['ID'];
  children?: Maybe<Array<Card>>;
  cost?: Maybe<Scalars['String']>;
  deck?: Maybe<Deck>;
  deckID?: Maybe<Scalars['ID']>;
  description?: Maybe<Scalars['String']>;
  hasActionsBoosterIcon: Scalars['Boolean'];
  hasArrow: Scalars['Boolean'];
  hasBonusPointIcon: Scalars['Boolean'];
  hasBreadIcon: Scalars['Boolean'];
  hasBuildingResourceProviderIcon: Scalars['Boolean'];
  hasCropProviderIcon: Scalars['Boolean'];
  hasCutPeatIcon: Scalars['Boolean'];
  hasFarmPlannerIcon: Scalars['Boolean'];
  hasFellTreesIcon: Scalars['Boolean'];
  hasFoodProviderIcon: Scalars['Boolean'];
  hasGoodsProviderIcon: Scalars['Boolean'];
  hasHiringFareIcon: Scalars['Boolean'];
  hasLivestockProviderIcon: Scalars['Boolean'];
  hasNegativeBonusPointIcon: Scalars['Boolean'];
  hasPanIcon: Scalars['Boolean'];
  hasPointsProviderIcon: Scalars['Boolean'];
  hasSlashAndBurnIcon: Scalars['Boolean'];
  id: Scalars['ID'];
  isOfficialJa: Scalars['Boolean'];
  literalID: Scalars['String'];
  minPlayersNumber?: Maybe<Scalars['Int']>;
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
  note?: Maybe<Scalars['String']>;
  playAgricolaCardID?: Maybe<Scalars['String']>;
  prerequisite?: Maybe<Scalars['String']>;
  printedID?: Maybe<Scalars['String']>;
  products?: Maybe<Array<Product>>;
  revision: Revision;
  revisionID: Scalars['ID'];
  specialVictoryPoint?: Maybe<Scalars['String']>;
  victoryPoint?: Maybe<Scalars['Int']>;
};

/** A connection to a list of items. */
export type CardConnection = {
  __typename?: 'CardConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<CardEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int'];
};

/** An edge in a connection. */
export type CardEdge = {
  __typename?: 'CardEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor'];
  /** The item at the end of the edge. */
  node?: Maybe<Card>;
};

export type CardSpecialColor = Node & {
  __typename?: 'CardSpecialColor';
  cards: CardConnection;
  id: Scalars['ID'];
  key: Scalars['String'];
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
};


export type CardSpecialColorCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};

/**
 * CardSpecialColorWhereInput is used for filtering CardSpecialColor objects.
 * Input was generated by ent.
 */
export type CardSpecialColorWhereInput = {
  and?: InputMaybe<Array<CardSpecialColorWhereInput>>;
  /** cards edge predicates */
  hasCards?: InputMaybe<Scalars['Boolean']>;
  hasCardsWith?: InputMaybe<Array<CardWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** key field predicates */
  key?: InputMaybe<Scalars['String']>;
  keyContains?: InputMaybe<Scalars['String']>;
  keyContainsFold?: InputMaybe<Scalars['String']>;
  keyEqualFold?: InputMaybe<Scalars['String']>;
  keyGT?: InputMaybe<Scalars['String']>;
  keyGTE?: InputMaybe<Scalars['String']>;
  keyHasPrefix?: InputMaybe<Scalars['String']>;
  keyHasSuffix?: InputMaybe<Scalars['String']>;
  keyIn?: InputMaybe<Array<Scalars['String']>>;
  keyLT?: InputMaybe<Scalars['String']>;
  keyLTE?: InputMaybe<Scalars['String']>;
  keyNEQ?: InputMaybe<Scalars['String']>;
  keyNotIn?: InputMaybe<Array<Scalars['String']>>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<CardSpecialColorWhereInput>;
  or?: InputMaybe<Array<CardSpecialColorWhereInput>>;
};

export type CardType = Node & {
  __typename?: 'CardType';
  cards: CardConnection;
  id: Scalars['ID'];
  key: Scalars['String'];
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
};


export type CardTypeCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};

/**
 * CardTypeWhereInput is used for filtering CardType objects.
 * Input was generated by ent.
 */
export type CardTypeWhereInput = {
  and?: InputMaybe<Array<CardTypeWhereInput>>;
  /** cards edge predicates */
  hasCards?: InputMaybe<Scalars['Boolean']>;
  hasCardsWith?: InputMaybe<Array<CardWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** key field predicates */
  key?: InputMaybe<Scalars['String']>;
  keyContains?: InputMaybe<Scalars['String']>;
  keyContainsFold?: InputMaybe<Scalars['String']>;
  keyEqualFold?: InputMaybe<Scalars['String']>;
  keyGT?: InputMaybe<Scalars['String']>;
  keyGTE?: InputMaybe<Scalars['String']>;
  keyHasPrefix?: InputMaybe<Scalars['String']>;
  keyHasSuffix?: InputMaybe<Scalars['String']>;
  keyIn?: InputMaybe<Array<Scalars['String']>>;
  keyLT?: InputMaybe<Scalars['String']>;
  keyLTE?: InputMaybe<Scalars['String']>;
  keyNEQ?: InputMaybe<Scalars['String']>;
  keyNotIn?: InputMaybe<Array<Scalars['String']>>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<CardTypeWhereInput>;
  or?: InputMaybe<Array<CardTypeWhereInput>>;
};

/**
 * CardWhereInput is used for filtering Card objects.
 * Input was generated by ent.
 */
export type CardWhereInput = {
  and?: InputMaybe<Array<CardWhereInput>>;
  /** card_special_color_id field predicates */
  cardSpecialColorID?: InputMaybe<Scalars['ID']>;
  cardSpecialColorIDIn?: InputMaybe<Array<Scalars['ID']>>;
  cardSpecialColorIDIsNil?: InputMaybe<Scalars['Boolean']>;
  cardSpecialColorIDNEQ?: InputMaybe<Scalars['ID']>;
  cardSpecialColorIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
  cardSpecialColorIDNotNil?: InputMaybe<Scalars['Boolean']>;
  /** card_type_id field predicates */
  cardTypeID?: InputMaybe<Scalars['ID']>;
  cardTypeIDIn?: InputMaybe<Array<Scalars['ID']>>;
  cardTypeIDNEQ?: InputMaybe<Scalars['ID']>;
  cardTypeIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** cost field predicates */
  cost?: InputMaybe<Scalars['String']>;
  costContains?: InputMaybe<Scalars['String']>;
  costContainsFold?: InputMaybe<Scalars['String']>;
  costEqualFold?: InputMaybe<Scalars['String']>;
  costGT?: InputMaybe<Scalars['String']>;
  costGTE?: InputMaybe<Scalars['String']>;
  costHasPrefix?: InputMaybe<Scalars['String']>;
  costHasSuffix?: InputMaybe<Scalars['String']>;
  costIn?: InputMaybe<Array<Scalars['String']>>;
  costIsNil?: InputMaybe<Scalars['Boolean']>;
  costLT?: InputMaybe<Scalars['String']>;
  costLTE?: InputMaybe<Scalars['String']>;
  costNEQ?: InputMaybe<Scalars['String']>;
  costNotIn?: InputMaybe<Array<Scalars['String']>>;
  costNotNil?: InputMaybe<Scalars['Boolean']>;
  /** deck_id field predicates */
  deckID?: InputMaybe<Scalars['ID']>;
  deckIDIn?: InputMaybe<Array<Scalars['ID']>>;
  deckIDIsNil?: InputMaybe<Scalars['Boolean']>;
  deckIDNEQ?: InputMaybe<Scalars['ID']>;
  deckIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
  deckIDNotNil?: InputMaybe<Scalars['Boolean']>;
  /** description field predicates */
  description?: InputMaybe<Scalars['String']>;
  descriptionContains?: InputMaybe<Scalars['String']>;
  descriptionContainsFold?: InputMaybe<Scalars['String']>;
  descriptionEqualFold?: InputMaybe<Scalars['String']>;
  descriptionGT?: InputMaybe<Scalars['String']>;
  descriptionGTE?: InputMaybe<Scalars['String']>;
  descriptionHasPrefix?: InputMaybe<Scalars['String']>;
  descriptionHasSuffix?: InputMaybe<Scalars['String']>;
  descriptionIn?: InputMaybe<Array<Scalars['String']>>;
  descriptionIsNil?: InputMaybe<Scalars['Boolean']>;
  descriptionLT?: InputMaybe<Scalars['String']>;
  descriptionLTE?: InputMaybe<Scalars['String']>;
  descriptionNEQ?: InputMaybe<Scalars['String']>;
  descriptionNotIn?: InputMaybe<Array<Scalars['String']>>;
  descriptionNotNil?: InputMaybe<Scalars['Boolean']>;
  /** has_actions_booster_icon field predicates */
  hasActionsBoosterIcon?: InputMaybe<Scalars['Boolean']>;
  hasActionsBoosterIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** ancestors edge predicates */
  hasAncestors?: InputMaybe<Scalars['Boolean']>;
  hasAncestorsWith?: InputMaybe<Array<CardWhereInput>>;
  /** has_arrow field predicates */
  hasArrow?: InputMaybe<Scalars['Boolean']>;
  hasArrowNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_bonus_point_icon field predicates */
  hasBonusPointIcon?: InputMaybe<Scalars['Boolean']>;
  hasBonusPointIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_bread_icon field predicates */
  hasBreadIcon?: InputMaybe<Scalars['Boolean']>;
  hasBreadIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_building_resource_provider_icon field predicates */
  hasBuildingResourceProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasBuildingResourceProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** card_special_color edge predicates */
  hasCardSpecialColor?: InputMaybe<Scalars['Boolean']>;
  hasCardSpecialColorWith?: InputMaybe<Array<CardSpecialColorWhereInput>>;
  /** card_type edge predicates */
  hasCardType?: InputMaybe<Scalars['Boolean']>;
  hasCardTypeWith?: InputMaybe<Array<CardTypeWhereInput>>;
  /** children edge predicates */
  hasChildren?: InputMaybe<Scalars['Boolean']>;
  hasChildrenWith?: InputMaybe<Array<CardWhereInput>>;
  /** has_crop_provider_icon field predicates */
  hasCropProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasCropProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_cut_peat_icon field predicates */
  hasCutPeatIcon?: InputMaybe<Scalars['Boolean']>;
  hasCutPeatIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** deck edge predicates */
  hasDeck?: InputMaybe<Scalars['Boolean']>;
  hasDeckWith?: InputMaybe<Array<DeckWhereInput>>;
  /** has_farm_planner_icon field predicates */
  hasFarmPlannerIcon?: InputMaybe<Scalars['Boolean']>;
  hasFarmPlannerIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_fell_trees_icon field predicates */
  hasFellTreesIcon?: InputMaybe<Scalars['Boolean']>;
  hasFellTreesIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_food_provider_icon field predicates */
  hasFoodProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasFoodProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_goods_provider_icon field predicates */
  hasGoodsProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasGoodsProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_hiring_fare_icon field predicates */
  hasHiringFareIcon?: InputMaybe<Scalars['Boolean']>;
  hasHiringFareIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_livestock_provider_icon field predicates */
  hasLivestockProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasLivestockProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_negative_bonus_point_icon field predicates */
  hasNegativeBonusPointIcon?: InputMaybe<Scalars['Boolean']>;
  hasNegativeBonusPointIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_pan_icon field predicates */
  hasPanIcon?: InputMaybe<Scalars['Boolean']>;
  hasPanIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** has_points_provider_icon field predicates */
  hasPointsProviderIcon?: InputMaybe<Scalars['Boolean']>;
  hasPointsProviderIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** products edge predicates */
  hasProducts?: InputMaybe<Scalars['Boolean']>;
  hasProductsWith?: InputMaybe<Array<ProductWhereInput>>;
  /** revision edge predicates */
  hasRevision?: InputMaybe<Scalars['Boolean']>;
  hasRevisionWith?: InputMaybe<Array<RevisionWhereInput>>;
  /** has_slash_and_burn_icon field predicates */
  hasSlashAndBurnIcon?: InputMaybe<Scalars['Boolean']>;
  hasSlashAndBurnIconNEQ?: InputMaybe<Scalars['Boolean']>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** is_official_ja field predicates */
  isOfficialJa?: InputMaybe<Scalars['Boolean']>;
  isOfficialJaNEQ?: InputMaybe<Scalars['Boolean']>;
  /** literal_id field predicates */
  literalID?: InputMaybe<Scalars['String']>;
  literalIDContains?: InputMaybe<Scalars['String']>;
  literalIDContainsFold?: InputMaybe<Scalars['String']>;
  literalIDEqualFold?: InputMaybe<Scalars['String']>;
  literalIDGT?: InputMaybe<Scalars['String']>;
  literalIDGTE?: InputMaybe<Scalars['String']>;
  literalIDHasPrefix?: InputMaybe<Scalars['String']>;
  literalIDHasSuffix?: InputMaybe<Scalars['String']>;
  literalIDIn?: InputMaybe<Array<Scalars['String']>>;
  literalIDLT?: InputMaybe<Scalars['String']>;
  literalIDLTE?: InputMaybe<Scalars['String']>;
  literalIDNEQ?: InputMaybe<Scalars['String']>;
  literalIDNotIn?: InputMaybe<Array<Scalars['String']>>;
  /** min_players_number field predicates */
  minPlayersNumber?: InputMaybe<Scalars['Int']>;
  minPlayersNumberGT?: InputMaybe<Scalars['Int']>;
  minPlayersNumberGTE?: InputMaybe<Scalars['Int']>;
  minPlayersNumberIn?: InputMaybe<Array<Scalars['Int']>>;
  minPlayersNumberIsNil?: InputMaybe<Scalars['Boolean']>;
  minPlayersNumberLT?: InputMaybe<Scalars['Int']>;
  minPlayersNumberLTE?: InputMaybe<Scalars['Int']>;
  minPlayersNumberNEQ?: InputMaybe<Scalars['Int']>;
  minPlayersNumberNotIn?: InputMaybe<Array<Scalars['Int']>>;
  minPlayersNumberNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<CardWhereInput>;
  /** note field predicates */
  note?: InputMaybe<Scalars['String']>;
  noteContains?: InputMaybe<Scalars['String']>;
  noteContainsFold?: InputMaybe<Scalars['String']>;
  noteEqualFold?: InputMaybe<Scalars['String']>;
  noteGT?: InputMaybe<Scalars['String']>;
  noteGTE?: InputMaybe<Scalars['String']>;
  noteHasPrefix?: InputMaybe<Scalars['String']>;
  noteHasSuffix?: InputMaybe<Scalars['String']>;
  noteIn?: InputMaybe<Array<Scalars['String']>>;
  noteIsNil?: InputMaybe<Scalars['Boolean']>;
  noteLT?: InputMaybe<Scalars['String']>;
  noteLTE?: InputMaybe<Scalars['String']>;
  noteNEQ?: InputMaybe<Scalars['String']>;
  noteNotIn?: InputMaybe<Array<Scalars['String']>>;
  noteNotNil?: InputMaybe<Scalars['Boolean']>;
  or?: InputMaybe<Array<CardWhereInput>>;
  /** play_agricola_card_id field predicates */
  playAgricolaCardID?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDContains?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDContainsFold?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDEqualFold?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDGT?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDGTE?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDHasPrefix?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDHasSuffix?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDIn?: InputMaybe<Array<Scalars['String']>>;
  playAgricolaCardIDIsNil?: InputMaybe<Scalars['Boolean']>;
  playAgricolaCardIDLT?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDLTE?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDNEQ?: InputMaybe<Scalars['String']>;
  playAgricolaCardIDNotIn?: InputMaybe<Array<Scalars['String']>>;
  playAgricolaCardIDNotNil?: InputMaybe<Scalars['Boolean']>;
  /** prerequisite field predicates */
  prerequisite?: InputMaybe<Scalars['String']>;
  prerequisiteContains?: InputMaybe<Scalars['String']>;
  prerequisiteContainsFold?: InputMaybe<Scalars['String']>;
  prerequisiteEqualFold?: InputMaybe<Scalars['String']>;
  prerequisiteGT?: InputMaybe<Scalars['String']>;
  prerequisiteGTE?: InputMaybe<Scalars['String']>;
  prerequisiteHasPrefix?: InputMaybe<Scalars['String']>;
  prerequisiteHasSuffix?: InputMaybe<Scalars['String']>;
  prerequisiteIn?: InputMaybe<Array<Scalars['String']>>;
  prerequisiteIsNil?: InputMaybe<Scalars['Boolean']>;
  prerequisiteLT?: InputMaybe<Scalars['String']>;
  prerequisiteLTE?: InputMaybe<Scalars['String']>;
  prerequisiteNEQ?: InputMaybe<Scalars['String']>;
  prerequisiteNotIn?: InputMaybe<Array<Scalars['String']>>;
  prerequisiteNotNil?: InputMaybe<Scalars['Boolean']>;
  /** printed_id field predicates */
  printedID?: InputMaybe<Scalars['String']>;
  printedIDContains?: InputMaybe<Scalars['String']>;
  printedIDContainsFold?: InputMaybe<Scalars['String']>;
  printedIDEqualFold?: InputMaybe<Scalars['String']>;
  printedIDGT?: InputMaybe<Scalars['String']>;
  printedIDGTE?: InputMaybe<Scalars['String']>;
  printedIDHasPrefix?: InputMaybe<Scalars['String']>;
  printedIDHasSuffix?: InputMaybe<Scalars['String']>;
  printedIDIn?: InputMaybe<Array<Scalars['String']>>;
  printedIDIsNil?: InputMaybe<Scalars['Boolean']>;
  printedIDLT?: InputMaybe<Scalars['String']>;
  printedIDLTE?: InputMaybe<Scalars['String']>;
  printedIDNEQ?: InputMaybe<Scalars['String']>;
  printedIDNotIn?: InputMaybe<Array<Scalars['String']>>;
  printedIDNotNil?: InputMaybe<Scalars['Boolean']>;
  /** revision_id field predicates */
  revisionID?: InputMaybe<Scalars['ID']>;
  revisionIDIn?: InputMaybe<Array<Scalars['ID']>>;
  revisionIDNEQ?: InputMaybe<Scalars['ID']>;
  revisionIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** special_victory_point field predicates */
  specialVictoryPoint?: InputMaybe<Scalars['String']>;
  specialVictoryPointContains?: InputMaybe<Scalars['String']>;
  specialVictoryPointContainsFold?: InputMaybe<Scalars['String']>;
  specialVictoryPointEqualFold?: InputMaybe<Scalars['String']>;
  specialVictoryPointGT?: InputMaybe<Scalars['String']>;
  specialVictoryPointGTE?: InputMaybe<Scalars['String']>;
  specialVictoryPointHasPrefix?: InputMaybe<Scalars['String']>;
  specialVictoryPointHasSuffix?: InputMaybe<Scalars['String']>;
  specialVictoryPointIn?: InputMaybe<Array<Scalars['String']>>;
  specialVictoryPointIsNil?: InputMaybe<Scalars['Boolean']>;
  specialVictoryPointLT?: InputMaybe<Scalars['String']>;
  specialVictoryPointLTE?: InputMaybe<Scalars['String']>;
  specialVictoryPointNEQ?: InputMaybe<Scalars['String']>;
  specialVictoryPointNotIn?: InputMaybe<Array<Scalars['String']>>;
  specialVictoryPointNotNil?: InputMaybe<Scalars['Boolean']>;
  /** victory_point field predicates */
  victoryPoint?: InputMaybe<Scalars['Int']>;
  victoryPointGT?: InputMaybe<Scalars['Int']>;
  victoryPointGTE?: InputMaybe<Scalars['Int']>;
  victoryPointIn?: InputMaybe<Array<Scalars['Int']>>;
  victoryPointIsNil?: InputMaybe<Scalars['Boolean']>;
  victoryPointLT?: InputMaybe<Scalars['Int']>;
  victoryPointLTE?: InputMaybe<Scalars['Int']>;
  victoryPointNEQ?: InputMaybe<Scalars['Int']>;
  victoryPointNotIn?: InputMaybe<Array<Scalars['Int']>>;
  victoryPointNotNil?: InputMaybe<Scalars['Boolean']>;
};

export type Deck = Node & {
  __typename?: 'Deck';
  cards: CardConnection;
  id: Scalars['ID'];
  key: Scalars['String'];
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
  revision: Revision;
  revisionID: Scalars['ID'];
};


export type DeckCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};

/**
 * DeckWhereInput is used for filtering Deck objects.
 * Input was generated by ent.
 */
export type DeckWhereInput = {
  and?: InputMaybe<Array<DeckWhereInput>>;
  /** cards edge predicates */
  hasCards?: InputMaybe<Scalars['Boolean']>;
  hasCardsWith?: InputMaybe<Array<CardWhereInput>>;
  /** revision edge predicates */
  hasRevision?: InputMaybe<Scalars['Boolean']>;
  hasRevisionWith?: InputMaybe<Array<RevisionWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** key field predicates */
  key?: InputMaybe<Scalars['String']>;
  keyContains?: InputMaybe<Scalars['String']>;
  keyContainsFold?: InputMaybe<Scalars['String']>;
  keyEqualFold?: InputMaybe<Scalars['String']>;
  keyGT?: InputMaybe<Scalars['String']>;
  keyGTE?: InputMaybe<Scalars['String']>;
  keyHasPrefix?: InputMaybe<Scalars['String']>;
  keyHasSuffix?: InputMaybe<Scalars['String']>;
  keyIn?: InputMaybe<Array<Scalars['String']>>;
  keyLT?: InputMaybe<Scalars['String']>;
  keyLTE?: InputMaybe<Scalars['String']>;
  keyNEQ?: InputMaybe<Scalars['String']>;
  keyNotIn?: InputMaybe<Array<Scalars['String']>>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<DeckWhereInput>;
  or?: InputMaybe<Array<DeckWhereInput>>;
  /** revision_id field predicates */
  revisionID?: InputMaybe<Scalars['ID']>;
  revisionIDIn?: InputMaybe<Array<Scalars['ID']>>;
  revisionIDNEQ?: InputMaybe<Scalars['ID']>;
  revisionIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID'];
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['Cursor']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['Cursor']>;
};

export type Product = Node & {
  __typename?: 'Product';
  cards: CardConnection;
  id: Scalars['ID'];
  isOfficialJa: Scalars['Boolean'];
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
  publishedYear?: Maybe<Scalars['Int']>;
  revision: Revision;
  revisionID: Scalars['ID'];
};


export type ProductCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};

/**
 * ProductWhereInput is used for filtering Product objects.
 * Input was generated by ent.
 */
export type ProductWhereInput = {
  and?: InputMaybe<Array<ProductWhereInput>>;
  /** cards edge predicates */
  hasCards?: InputMaybe<Scalars['Boolean']>;
  hasCardsWith?: InputMaybe<Array<CardWhereInput>>;
  /** revision edge predicates */
  hasRevision?: InputMaybe<Scalars['Boolean']>;
  hasRevisionWith?: InputMaybe<Array<RevisionWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** is_official_ja field predicates */
  isOfficialJa?: InputMaybe<Scalars['Boolean']>;
  isOfficialJaNEQ?: InputMaybe<Scalars['Boolean']>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<ProductWhereInput>;
  or?: InputMaybe<Array<ProductWhereInput>>;
  /** published_year field predicates */
  publishedYear?: InputMaybe<Scalars['Int']>;
  publishedYearGT?: InputMaybe<Scalars['Int']>;
  publishedYearGTE?: InputMaybe<Scalars['Int']>;
  publishedYearIn?: InputMaybe<Array<Scalars['Int']>>;
  publishedYearIsNil?: InputMaybe<Scalars['Boolean']>;
  publishedYearLT?: InputMaybe<Scalars['Int']>;
  publishedYearLTE?: InputMaybe<Scalars['Int']>;
  publishedYearNEQ?: InputMaybe<Scalars['Int']>;
  publishedYearNotIn?: InputMaybe<Array<Scalars['Int']>>;
  publishedYearNotNil?: InputMaybe<Scalars['Boolean']>;
  /** revision_id field predicates */
  revisionID?: InputMaybe<Scalars['ID']>;
  revisionIDIn?: InputMaybe<Array<Scalars['ID']>>;
  revisionIDNEQ?: InputMaybe<Scalars['ID']>;
  revisionIDNotIn?: InputMaybe<Array<Scalars['ID']>>;
};

export type Query = {
  __typename?: 'Query';
  cardSpecialColors: Array<CardSpecialColor>;
  cardTypes: Array<CardType>;
  cards: CardConnection;
  decks: Array<Deck>;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  products: Array<Product>;
  revisions: Array<Revision>;
};


export type QueryCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};


export type QueryNodeArgs = {
  id: Scalars['ID'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']>;
};

export type Revision = Node & {
  __typename?: 'Revision';
  cards: CardConnection;
  decks?: Maybe<Array<Deck>>;
  id: Scalars['ID'];
  key: Scalars['String'];
  nameEn?: Maybe<Scalars['String']>;
  nameJa?: Maybe<Scalars['String']>;
  products?: Maybe<Array<Product>>;
};


export type RevisionCardsArgs = {
  after?: InputMaybe<Scalars['Cursor']>;
  before?: InputMaybe<Scalars['Cursor']>;
  first?: InputMaybe<Scalars['Int']>;
  last?: InputMaybe<Scalars['Int']>;
  where?: InputMaybe<CardWhereInput>;
};

/**
 * RevisionWhereInput is used for filtering Revision objects.
 * Input was generated by ent.
 */
export type RevisionWhereInput = {
  and?: InputMaybe<Array<RevisionWhereInput>>;
  /** cards edge predicates */
  hasCards?: InputMaybe<Scalars['Boolean']>;
  hasCardsWith?: InputMaybe<Array<CardWhereInput>>;
  /** decks edge predicates */
  hasDecks?: InputMaybe<Scalars['Boolean']>;
  hasDecksWith?: InputMaybe<Array<DeckWhereInput>>;
  /** products edge predicates */
  hasProducts?: InputMaybe<Scalars['Boolean']>;
  hasProductsWith?: InputMaybe<Array<ProductWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']>;
  idGT?: InputMaybe<Scalars['ID']>;
  idGTE?: InputMaybe<Scalars['ID']>;
  idIn?: InputMaybe<Array<Scalars['ID']>>;
  idLT?: InputMaybe<Scalars['ID']>;
  idLTE?: InputMaybe<Scalars['ID']>;
  idNEQ?: InputMaybe<Scalars['ID']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']>>;
  /** key field predicates */
  key?: InputMaybe<Scalars['String']>;
  keyContains?: InputMaybe<Scalars['String']>;
  keyContainsFold?: InputMaybe<Scalars['String']>;
  keyEqualFold?: InputMaybe<Scalars['String']>;
  keyGT?: InputMaybe<Scalars['String']>;
  keyGTE?: InputMaybe<Scalars['String']>;
  keyHasPrefix?: InputMaybe<Scalars['String']>;
  keyHasSuffix?: InputMaybe<Scalars['String']>;
  keyIn?: InputMaybe<Array<Scalars['String']>>;
  keyLT?: InputMaybe<Scalars['String']>;
  keyLTE?: InputMaybe<Scalars['String']>;
  keyNEQ?: InputMaybe<Scalars['String']>;
  keyNotIn?: InputMaybe<Array<Scalars['String']>>;
  /** name_en field predicates */
  nameEn?: InputMaybe<Scalars['String']>;
  nameEnContains?: InputMaybe<Scalars['String']>;
  nameEnContainsFold?: InputMaybe<Scalars['String']>;
  nameEnEqualFold?: InputMaybe<Scalars['String']>;
  nameEnGT?: InputMaybe<Scalars['String']>;
  nameEnGTE?: InputMaybe<Scalars['String']>;
  nameEnHasPrefix?: InputMaybe<Scalars['String']>;
  nameEnHasSuffix?: InputMaybe<Scalars['String']>;
  nameEnIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnIsNil?: InputMaybe<Scalars['Boolean']>;
  nameEnLT?: InputMaybe<Scalars['String']>;
  nameEnLTE?: InputMaybe<Scalars['String']>;
  nameEnNEQ?: InputMaybe<Scalars['String']>;
  nameEnNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameEnNotNil?: InputMaybe<Scalars['Boolean']>;
  /** name_ja field predicates */
  nameJa?: InputMaybe<Scalars['String']>;
  nameJaContains?: InputMaybe<Scalars['String']>;
  nameJaContainsFold?: InputMaybe<Scalars['String']>;
  nameJaEqualFold?: InputMaybe<Scalars['String']>;
  nameJaGT?: InputMaybe<Scalars['String']>;
  nameJaGTE?: InputMaybe<Scalars['String']>;
  nameJaHasPrefix?: InputMaybe<Scalars['String']>;
  nameJaHasSuffix?: InputMaybe<Scalars['String']>;
  nameJaIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaIsNil?: InputMaybe<Scalars['Boolean']>;
  nameJaLT?: InputMaybe<Scalars['String']>;
  nameJaLTE?: InputMaybe<Scalars['String']>;
  nameJaNEQ?: InputMaybe<Scalars['String']>;
  nameJaNotIn?: InputMaybe<Array<Scalars['String']>>;
  nameJaNotNil?: InputMaybe<Scalars['Boolean']>;
  not?: InputMaybe<RevisionWhereInput>;
  or?: InputMaybe<Array<RevisionWhereInput>>;
};

export type GetCardsDetailByRevisionQueryVariables = Exact<{
  revisionID: Scalars['ID'];
}>;


export type GetCardsDetailByRevisionQuery = { __typename?: 'Query', cards: { __typename?: 'CardConnection', totalCount: number, edges?: Array<{ __typename?: 'CardEdge', node?: { __typename?: 'Card', literalID: string, printedID?: string | null, playAgricolaCardID?: string | null, nameJa?: string | null, nameEn?: string | null, minPlayersNumber?: number | null, prerequisite?: string | null, cost?: string | null, description?: string | null, note?: string | null, isOfficialJa: boolean, victoryPoint?: number | null, specialVictoryPoint?: string | null, hasArrow: boolean, hasBonusPointIcon: boolean, hasNegativeBonusPointIcon: boolean, hasPanIcon: boolean, hasBreadIcon: boolean, hasFarmPlannerIcon: boolean, hasActionsBoosterIcon: boolean, hasPointsProviderIcon: boolean, hasGoodsProviderIcon: boolean, hasFoodProviderIcon: boolean, hasCropProviderIcon: boolean, hasBuildingResourceProviderIcon: boolean, hasLivestockProviderIcon: boolean, hasCutPeatIcon: boolean, hasFellTreesIcon: boolean, hasSlashAndBurnIcon: boolean, hasHiringFareIcon: boolean, deck?: { __typename?: 'Deck', id: string, nameJa?: string | null } | null, products?: Array<{ __typename?: 'Product', id: string, nameJa?: string | null }> | null, cardType: { __typename?: 'CardType', key: string, nameJa?: string | null }, cardSpecialColor?: { __typename?: 'CardSpecialColor', key: string } | null, children?: Array<{ __typename?: 'Card', literalID: string, printedID?: string | null, nameJa?: string | null, revision: { __typename?: 'Revision', id: string, key: string } }> | null, ancestors?: Array<{ __typename?: 'Card', literalID: string, printedID?: string | null, nameJa?: string | null, revision: { __typename?: 'Revision', id: string, key: string } }> | null } | null } | null> | null } };

export type GetCardsListByRevisionQueryVariables = Exact<{
  revisionID: Scalars['ID'];
  after?: InputMaybe<Scalars['Cursor']>;
}>;


export type GetCardsListByRevisionQuery = { __typename?: 'Query', cards: { __typename?: 'CardConnection', totalCount: number, edges?: Array<{ __typename?: 'CardEdge', node?: { __typename?: 'Card', literalID: string, printedID?: string | null, nameJa?: string | null, nameEn?: string | null, cardType: { __typename?: 'CardType', key: string }, cardSpecialColor?: { __typename?: 'CardSpecialColor', key: string } | null } | null } | null> | null, pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, hasPreviousPage: boolean, endCursor?: any | null } } };


export const GetCardsDetailByRevisionDocument = gql`
    query GetCardsDetailByRevision($revisionID: ID!) {
  cards(where: {revisionID: $revisionID}) {
    edges {
      node {
        literalID
        printedID
        playAgricolaCardID
        deck {
          id
          nameJa
        }
        products {
          id
          nameJa
        }
        cardType {
          key
          nameJa
        }
        cardSpecialColor {
          key
        }
        nameJa
        nameEn
        minPlayersNumber
        prerequisite
        cost
        description
        note
        isOfficialJa
        victoryPoint
        specialVictoryPoint
        hasArrow
        hasBonusPointIcon
        hasNegativeBonusPointIcon
        hasPanIcon
        hasBreadIcon
        hasFarmPlannerIcon
        hasActionsBoosterIcon
        hasPointsProviderIcon
        hasGoodsProviderIcon
        hasFoodProviderIcon
        hasCropProviderIcon
        hasBuildingResourceProviderIcon
        hasLivestockProviderIcon
        hasCutPeatIcon
        hasFellTreesIcon
        hasSlashAndBurnIcon
        hasHiringFareIcon
        children {
          revision {
            id
            key
          }
          literalID
          printedID
          nameJa
        }
        ancestors {
          revision {
            id
            key
          }
          literalID
          printedID
          nameJa
        }
      }
    }
    totalCount
  }
}
    `;
export const GetCardsListByRevisionDocument = gql`
    query GetCardsListByRevision($revisionID: ID!, $after: Cursor) {
  cards(where: {revisionID: $revisionID}, first: 30, after: $after) {
    edges {
      node {
        literalID
        printedID
        cardType {
          key
        }
        cardSpecialColor {
          key
        }
        nameJa
        nameEn
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
    }
    totalCount
  }
}
    `;

export type SdkFunctionWrapper = <T>(action: (requestHeaders?:Record<string, string>) => Promise<T>, operationName: string, operationType?: string) => Promise<T>;


const defaultWrapper: SdkFunctionWrapper = (action, _operationName, _operationType) => action();

export function getSdk(client: GraphQLClient, withWrapper: SdkFunctionWrapper = defaultWrapper) {
  return {
    GetCardsDetailByRevision(variables: GetCardsDetailByRevisionQueryVariables, requestHeaders?: Dom.RequestInit["headers"]): Promise<GetCardsDetailByRevisionQuery> {
      return withWrapper((wrappedRequestHeaders) => client.request<GetCardsDetailByRevisionQuery>(GetCardsDetailByRevisionDocument, variables, {...requestHeaders, ...wrappedRequestHeaders}), 'GetCardsDetailByRevision', 'query');
    },
    GetCardsListByRevision(variables: GetCardsListByRevisionQueryVariables, requestHeaders?: Dom.RequestInit["headers"]): Promise<GetCardsListByRevisionQuery> {
      return withWrapper((wrappedRequestHeaders) => client.request<GetCardsListByRevisionQuery>(GetCardsListByRevisionDocument, variables, {...requestHeaders, ...wrappedRequestHeaders}), 'GetCardsListByRevision', 'query');
    }
  };
}
export type Sdk = ReturnType<typeof getSdk>;