name: ci-main

on:
  push:
    branches:
      - main

jobs:
  test-node:
    uses: ./.github/workflows/test-node.yml

  test-actions:
    uses: ./.github/workflows/test-actions.yml

  test-codegen:
    uses: ./.github/workflows/test-codegen.yml
