name: on push main

on:
  push:
    branches:
      - main

jobs:
  test-node:
    uses: ./.github/workflows/wf-test-node.yml

  deploy:
    uses: ./.github/workflows/wf-deploy.yml
    secrets: inherit
    with:
      environment: production
