name: on push main

on:
  push:
    branches:
      - main

jobs:
  test-node:
    uses: ./.github/workflows/wf-test-node.yml

  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 792029
          private-key: ${{ secrets.AGRICOLADEVJP_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
