name: on release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-node:
    uses: ./.github/workflows/wf-test-node.yml

  dispatch-deploy:
    needs: [test-node]
    uses: ./.github/workflows/wf-dispatch-deploy.yml
    secrets: inherit
