name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read
  deployments: write

concurrency:
  group: ${{ inputs.environment }}

env:
  TZ: Asia/Tokyo

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      server:
        image: ghcr.io/agricoladevjp/agricoladb-server/server:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 5s
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build --site https://db.agricolajp.dev
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: d8ffa051ff726193056507455bf58eb1
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: agricoladb-viewer
          directory: dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
