name: test-node

on:
  workflow_call:

env:
  TZ: Asia/Tokyo

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm eslint:check

  build:
    runs-on: ubuntu-latest
    services:
      server:
        image: ghcr.io/agricoladevjp/agricoladb-server/server:2.0.4
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 5s
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
